name: Deploy Next.js to cPanel (standalone)

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build (force webpack for stability)
        run: npx next build

      - name: Prepare upload bundle
        run: |
          mkdir -p out_upload
          cp -r .next/standalone/* out_upload/
          mkdir -p out_upload/.next/static
          cp -r .next/static/* out_upload/.next/static/
          if [ -d public ]; then cp -r public out_upload/public; fi

      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: out_upload
          server-dir: pms.muhdev.com/